api_platform:
    collection:
        pagination:
            page_parameter_name: _page
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [ 3 ]
        api_keys:
            JWT:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        pagination_items_per_page: 2
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
