vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        annonce_imageFile:
            uri_prefix: /uploads/images_annonces
            upload_destination: '%kernel.project_dir%/public/uploads/images_annonces'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
